# Generated by Django 4.2.20 on 2025-03-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Este campo precisa estar marcado parapublicação aparecer no blog.'),
        ),
    ]
