# Generated by Django 4.2.20 on 2025-03-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_page_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Este campo precisa estar marcado para publicação aparecer no blog.'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('slug', models.SlugField(blank=True, default='', max_length=65, unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Este campo precisa estar marcado para publicação aparecer no blog.')),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, default='', upload_to='post/Y%/%m/')),
                ('cover_in_posts_content', models.BooleanField(default=True, help_text='Exibir a imagem de capa também dentro do conteúdo do post?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, default='', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
