# Generated by Django 4.2.20 on 2025-03-07 00:30

from django.db import migrations, models
import site_setup.utils.models_validator


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[site_setup.utils.models_validator.validate_png]),
        ),
    ]
